// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-seckill/app/model/internal"
)

// Product is the golang structure for table product.
type Product internal.Product

// Fill with you ideas below.
