// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-seckill/app/model/internal"
)

// UserProductRef is the golang structure for table user_product_ref.
type UserProductRef internal.UserProductRef

// Fill with you ideas below.
