// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id          int         `orm:"id,primary"   json:"id"`           //
	ProductName string      `orm:"product_name" json:"product_name"` // 商品名称
	ProductNum  int         `orm:"product_num"  json:"product_num"`  // 商品数量
	Status      int         `orm:"status"       json:"status"`       // 商品的状态 0：停止 1：正常
	StartAt     *gtime.Time `orm:"start_at"     json:"start_at"`     // 活动开始时间
	EndAt       *gtime.Time `orm:"end_at"       json:"end_at"`       // 活动结束时间
	CreateAt    *gtime.Time `orm:"create_at"    json:"create_at"`    //
	UpdateAt    *gtime.Time `orm:"update_at"    json:"update_at"`    //
}
