// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	Username  string      `orm:"username"   json:"username"`  // 用户名
	Password  string      `orm:"password"   json:"password"`  // 密码
	Telephone string      `orm:"telephone"  json:"telephone"` // 手机号
	CreateAt  *gtime.Time `orm:"create_at"  json:"create_at"` //
	UpdateAt  *gtime.Time `orm:"update_at"  json:"update_at"` //
}
