// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserProductRef is the golang structure for table user_product_ref.
type UserProductRef struct {
	Id        int         `orm:"id,primary" json:"id"`         //
	UserId    int         `orm:"user_id"    json:"user_id"`    // 用户ID
	ProductId int         `orm:"product_id" json:"product_id"` // 产品ID
	CreateAt  *gtime.Time `orm:"create_at"  json:"create_at"`  //
	UpdateAt  *gtime.Time `orm:"update_at"  json:"update_at"`  //
}
