// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-seckill/app/dao/internal"
)

// userProductRefDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userProductRefDao struct {
	*internal.UserProductRefDao
}

var (
	// UserProductRef is globally public accessible object for table user_product_ref operations.
	UserProductRef = &userProductRefDao{
		internal.UserProductRef,
	}
)

// Fill with you ideas below.
