---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2022/3/17 14:05
---
if redis.call("exists", KEYS[1]) == 1 then
    return 1
else
    if redis.call("set", KEYS[1], "ex", KEYS[2]) == "OK" then
        return 0
    else
        return 0
    end
end